# -*- coding: utf-8 -*-
"""Email Sender.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_on4ZWrEUMM0RMbtErzPAFeLkcWPGVWT
"""

def fact(n):
  if n==1:
    return 1
  else:
    return n*fact(n-1)
print(fact(5))

pip install --upgrade openai

from openai import OpenAI
client = OpenAI()

response = client.chat.completions.create(
  model="gpt-4",
  messages=[
    {
      "role": "user",
      "content": "Make a single page website that shows off different neat javascript features for drop-downs and things to display information. The website should be an HTML file with embedded javascript and CSS."
    }
  ],
  temperature=0.7,
  max_tokens=64,
  top_p=1
)



setx OPENAI_API_KEY "sk-proj-Lt13Cwu8wO8Dj9ecN1PfT3BlbkFJCgC2BknG00yH6E6gcyC8"



def fib(n):
  if n==0:
    return 0
  elif n==1:
    return 1
  else:
    return fib(n-1)+fib(n-2)
print(fib(3))

def pattern(n):
  for i in range(n,-1,-1):
    for j in range(0,i+1):
      print("* ", end="")
    print("\r")
pattern(5)

import smtplib
from email.message import EmailMessage
import ssl
import os

email_sender = 'tuhinbdesh@gmail.com'#'noc@mos5tel.com''tuhinbdesh@gmail.com'
email_password = 'uvxn qkzh vcar xpgc'#'WPJRW1DCT0Vn'#'uvxn qkzh vcar xpgc'#os.environ.get("EMAIL_PASSWORD")
email_receiver = ['tuhinbdesh@gmail.com','noc@mos5tel.com','babul_bd2003@yahoo.com']

subject = 'Check out the message'
body = """
This for test mail
"""
em=EmailMessage()
em['From'] = email_sender
em['To'] = email_receiver
em['Subject'] = subject

em.set_content(body)

context = ssl.create_default_context()


with smtplib.SMTP_SSL('smtp.gmail.com', 465, context=context) as smtp:
    smtp.login(email_sender,email_password)
    smtp.sendmail(email_sender,email_receiver,em.as_string())